name: Test

on:
  pull_request:
    branches: [master]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Start app
        run: npm run start &
        env:
          TERM: xterm

      - name: Wait for server
        run: npx wait-on http://localhost:3001 --timeout 60000

      - name: Run Cypress tests
        run: npm run test:e2e

      - name: Upload tests report (cypress mochaawesome merged HTML report)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: reports
